"""MCP Tools module.

This module exports tool implementations and tool schemas for the MCP server.
"""

# Re-export all tool implementations from the original tools module
# Export tool schemas
from magaldi_mcp.tools.schemas import ALL_TOOL_SCHEMAS
from magaldi_mcp.tools_impl import (
    batch_get_elements,
    dependency_graph,
    explain_element,
    find_async_code,
    find_by_pattern,
    find_call_chain,
    find_callers,
    find_complex_functions,
    find_dead_code,
    find_dependencies,
    find_dependents,
    find_entry_points,
    find_env_usage,
    find_files,
    find_implementations,
    find_security_issues,
    find_similar,
    find_undocumented,
    find_usages,
    generate_config,
    generate_skill,
    get_call_graph,
    get_children,
    get_command_tree,
    get_context,
    get_element,
    get_feature_members,
    get_file_structure,
    get_glossary_term,
    get_repo_stats,
    get_route_tree,
    list_features,
    list_glossary,
    list_patterns,
    list_repos,
    pattern_search,
    search_code,
    search_features,
    search_glossary,
    mcp_self_review,
)
from magaldi_mcp.tools.parser_lab import (
    parser_lab_analyze,
    parser_lab_create_test,
    parser_lab_run_tests,
    parser_lab_suggest_fix,
)

__all__ = [
    # Tool implementations
    "batch_get_elements",
    "dependency_graph",
    "explain_element",
    "find_async_code",
    "find_by_pattern",
    "find_call_chain",
    "find_callers",
    "find_complex_functions",
    "find_dead_code",
    "find_dependencies",
    "find_dependents",
    "find_entry_points",
    "find_env_usage",
    "find_files",
    "find_implementations",
    "find_security_issues",
    "find_similar",
    "find_undocumented",
    "find_usages",
    "generate_config",
    "generate_skill",
    "get_call_graph",
    "get_children",
    "get_command_tree",
    "get_context",
    "get_element",
    "get_feature_members",
    "get_file_structure",
    "get_glossary_term",
    "get_repo_stats",
    "get_route_tree",
    "list_features",
    "list_glossary",
    "list_patterns",
    "list_repos",
    "pattern_search",
    "search_code",
    "search_features",
    "search_glossary",
    # Labs tools
    "mcp_self_review",
    # Parser Lab tools
    "parser_lab_analyze",
    "parser_lab_create_test",
    "parser_lab_run_tests",
    "parser_lab_suggest_fix",
    # Tool schemas
    "ALL_TOOL_SCHEMAS",
]
